"""
Offline GNN training script.

Trains the PhysicsGNN on trajectory data generated by ``gnn/generate_data.py``.

Usage
-----
    python gnn/train_gnn.py --config configs/real.yaml \\
        --use_gnn_world_model true --gnn_train true \\
        --gnn_data_dir data/gnn/ --gnn_checkpoint_dir checkpoints/gnn/

Training details:
    * Adam optimiser, lr=1e-4, cosine annealing schedule, 100 epochs
    * Batch by trajectory, unroll 10 frames (truncated BPTT)
    * Loss: MSE on velocity delta predictions vs Warp ground truth
    * Gaussian noise injection (σ=0.003 m) on positions/velocities
    * Best checkpoint saved by validation loss
    * Optional WandB logging (uses existing project config)
"""

from __future__ import annotations

import argparse
import json
import math
import os
import pickle
import random
import sys
from typing import List, Optional

import numpy as np
import torch
import torch.nn as nn

_PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
if _PROJECT_ROOT not in sys.path:
    sys.path.insert(0, _PROJECT_ROOT)

from qqtt.utils import cfg, logger

from gnn.model import PhysicsGNN
from gnn.utils import build_graph_from_sim_state, save_gnn_checkpoint

# ──────────────────────────────────────────────────────────────
# Dataset helpers
# ──────────────────────────────────────────────────────────────

def _load_split(data_dir: str):
    """Load train/val split indices and trajectory paths.

    Returns
    -------
    (train_paths, val_paths) – lists of .pkl file paths.
    """
    split_path = os.path.join(data_dir, "split.json")
    assert os.path.exists(split_path), f"Split file not found: {split_path}"
    with open(split_path, "r") as f:
        split = json.load(f)
    train_paths = [os.path.join(data_dir, f"traj_{i:05d}.pkl") for i in split["train"]]
    val_paths = [os.path.join(data_dir, f"traj_{i:05d}.pkl") for i in split["val"]]
    return train_paths, val_paths


def _load_trajectory(path: str):
    """Load a single trajectory .pkl file.

    Returns
    -------
    list of frame-snapshot dicts.
    """
    with open(path, "rb") as f:
        return pickle.load(f)


# ──────────────────────────────────────────────────────────────
# Training / eval loops
# ──────────────────────────────────────────────────────────────

_NOISE_STD = 0.003  # metres – for input noise injection


def _random_rotation_matrix_small(max_angle_rad: float, device: str) -> torch.Tensor:
    """Sample a small random rotation matrix (axis-angle, random axis)."""
    import math as _math
    axis = torch.randn(3, device=device)
    axis = axis / axis.norm().clamp(min=1e-8)
    angle = torch.empty(1, device=device).uniform_(-max_angle_rad, max_angle_rad).item()
    K = torch.zeros(3, 3, device=device)
    K[0, 1] = -axis[2]; K[0, 2] = axis[1]
    K[1, 0] = axis[2];  K[1, 2] = -axis[0]
    K[2, 0] = -axis[1]; K[2, 1] = axis[0]
    R = torch.eye(3, device=device) + _math.sin(angle) * K + (1 - _math.cos(angle)) * (K @ K)
    return R


def _augment_snapshot_positions(snap: dict, R: torch.Tensor, t_offset: torch.Tensor, device: str) -> dict:
    """Apply rigid body transform (rotation R + translation t) to positions/velocities in a snapshot.

    Returns a NEW dict with transformed tensors (does not modify original).
    """
    snap_aug = dict(snap)  # shallow copy
    for key in ["positions", "next_positions"]:
        p = snap[key].to(device).float()
        snap_aug[key] = (p @ R.T + t_offset).cpu()
    for key in ["velocities", "next_velocities", "delta_v"]:
        v = snap[key].to(device).float()
        snap_aug[key] = (v @ R.T).cpu()
    return snap_aug


def _unrolled_loss(
    model: PhysicsGNN,
    snapshots: list,
    start: int,
    length: int,
    device: str,
    add_noise: bool = True,
    enable_breakage: bool = False,
) -> torch.Tensor:
    """Compute MSE loss over an unrolled window of *length* frames.

    Parameters
    ----------
    model : PhysicsGNN
    snapshots : trajectory list from ``_load_trajectory``.
    start : int – starting frame index within trajectory.
    length : int – number of frames to unroll.
    device : str
    add_noise : bool – inject Gaussian noise on inputs.
    enable_breakage : bool

    Returns
    -------
    Scalar loss tensor.
    """
    total_loss = torch.tensor(0.0, device=device)
    count = 0

    snap = snapshots[start]
    pos = snap["positions"].to(device).float()
    vel = snap["velocities"].to(device).float()

    for t in range(start, min(start + length, len(snapshots))):
        snap_t = snapshots[t]

        # Noise injection (GNS-style)
        if add_noise:
            pos = pos + torch.randn_like(pos) * _NOISE_STD
            vel = vel + torch.randn_like(vel) * _NOISE_STD

        edge_idx = snap_t["edge_indices"].to(device).long()
        rest_len = snap_t["rest_lengths"].to(device).float()
        s_Y = snap_t["spring_Y_log"].to(device).float()
        ys = snap_t["yield_strain"].to(device).float()
        hf = snap_t["hardening_factor"].to(device).float()
        bs = snap_t.get("break_strain")
        if bs is not None:
            bs = bs.to(device).float()
        ic = snap_t["is_controller"].to(device).float()
        dt_frame = snap_t["dt_frame"]

        gt_delta_v = snap_t["delta_v"].to(device).float()

        # Build graph
        graph = build_graph_from_sim_state(
            pos, vel, edge_idx, rest_len, s_Y, ys, hf, bs, ic, enable_breakage,
        )

        pred_delta_v = model(
            graph["node_features"],
            graph["edge_features"],
            graph["edge_index"],
        )

        mse = nn.functional.mse_loss(pred_delta_v, gt_delta_v)
        total_loss = total_loss + mse
        count += 1

        # Teacher-forced next state for next iteration
        next_snap = snapshots[t]
        pos = next_snap["next_positions"].to(device).float()
        vel = next_snap["next_velocities"].to(device).float()

    return total_loss / max(count, 1)


def _eval_epoch(
    model: PhysicsGNN,
    paths: List[str],
    device: str,
    unroll_len: int = 10,
    enable_breakage: bool = False,
) -> float:
    """Evaluate model on a set of trajectories and return mean loss.

    Parameters
    ----------
    model : PhysicsGNN
    paths : list of trajectory .pkl paths
    device : str
    unroll_len : int
    enable_breakage : bool

    Returns
    -------
    float – mean MSE loss.
    """
    model.eval()
    total = 0.0
    n = 0
    with torch.no_grad():
        for p in paths:
            traj = _load_trajectory(p)
            if len(traj) == 0:
                continue
            for start in range(0, len(traj), unroll_len):
                loss = _unrolled_loss(
                    model, traj, start, unroll_len, device,
                    add_noise=False, enable_breakage=enable_breakage,
                )
                total += loss.item()
                n += 1
    return total / max(n, 1)


# ──────────────────────────────────────────────────────────────
# Main training procedure
# ──────────────────────────────────────────────────────────────

def run_gnn_training(args: Optional[argparse.Namespace] = None) -> None:
    """Train the PhysicsGNN offline on Warp-generated data.

    Parameters
    ----------
    args : Namespace (unused beyond initial config loading; all
           parameters are read from ``cfg``).
    """
    device = getattr(cfg, "device", "cuda:0")
    data_dir = cfg.gnn_data_dir
    ckpt_dir = cfg.gnn_checkpoint_dir
    epochs = cfg.gnn_epochs
    lr = cfg.gnn_lr
    hidden_dim = cfg.gnn_hidden_dim
    mp_steps = cfg.gnn_message_passing_steps
    enable_breakage = getattr(cfg, "enable_breakage", False)
    unroll_len = getattr(cfg, "gnn_unroll_len", 3)  # short unrolls save GPU memory

    os.makedirs(ckpt_dir, exist_ok=True)
    train_paths, val_paths = _load_split(data_dir)
    logger.info(f"GNN training: {len(train_paths)} train / {len(val_paths)} val trajectories")

    # Infer input dims from first snapshot
    sample_traj = _load_trajectory(train_paths[0])
    sample_snap = sample_traj[0]
    input_edge_dim = 9 + (1 if enable_breakage else 0)  # base 9, +1 for break_strain
    input_node_dim = 10

    model = PhysicsGNN(
        input_node_dim=input_node_dim,
        input_edge_dim=input_edge_dim,
        hidden_dim=hidden_dim,
        message_passing_steps=mp_steps,
    ).to(device)

    optimizer = torch.optim.Adam(model.parameters(), lr=lr)
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=epochs)

    # Optional WandB
    use_wandb = False
    try:
        import wandb
        if wandb.run is not None or os.environ.get("WANDB_PROJECT"):
            wandb.init(project=os.environ.get("WANDB_PROJECT", "chiptwin-gnn"), reinit=True)
            use_wandb = True
    except ImportError:
        pass

    best_val = float("inf")

    for epoch in range(1, epochs + 1):
        model.train()
        random.shuffle(train_paths)
        epoch_loss = 0.0
        n_batches = 0

        for traj_path in train_paths:
            traj = _load_trajectory(traj_path)
            if len(traj) == 0:
                continue

            # ── Per-trajectory rigid body augmentation ──
            # Random small rotation + translation teaches spatial equivariance
            # and prevents the GNN from memorising absolute coordinates.
            R_aug = _random_rotation_matrix_small(math.radians(15), device)
            t_aug = torch.randn(3, device=device) * 0.010  # ~10 mm shift
            traj = [_augment_snapshot_positions(s, R_aug, t_aug, device) for s in traj]

            for start in range(0, len(traj), unroll_len):
                optimizer.zero_grad()
                loss = _unrolled_loss(
                    model, traj, start, unroll_len, device,
                    add_noise=True, enable_breakage=enable_breakage,
                )
                loss.backward()
                torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
                optimizer.step()
                epoch_loss += loss.item()
                n_batches += 1

            # Free intermediate activations between trajectories
            del traj
            torch.cuda.empty_cache()

        scheduler.step()
        mean_train = epoch_loss / max(n_batches, 1)

        # Validation
        val_loss = _eval_epoch(model, val_paths, device, unroll_len, enable_breakage)

        lr_now = scheduler.get_last_lr()[0]
        logger.info(
            f"[GNN] Epoch {epoch:3d}/{epochs}  train_loss={mean_train:.6f}  "
            f"val_loss={val_loss:.6f}  lr={lr_now:.2e}"
        )

        if use_wandb:
            wandb.log({"gnn/train_loss": mean_train, "gnn/val_loss": val_loss, "gnn/lr": lr_now, "epoch": epoch})

        if val_loss < best_val:
            best_val = val_loss
            best_path = os.path.join(ckpt_dir, "best_gnn.pth")
            save_gnn_checkpoint(model, best_path, epoch=epoch, val_loss=val_loss)
            logger.info(f"  ✓ New best val={val_loss:.6f}, saved → {best_path}")

    # Save final
    final_path = os.path.join(ckpt_dir, "final_gnn.pth")
    save_gnn_checkpoint(model, final_path, epoch=epochs, val_loss=best_val)
    logger.info(f"Training complete.  Best val_loss={best_val:.6f}")

    if use_wandb:
        wandb.finish()


# ──────────────────────────────────────────────────────────────
# CLI
# ──────────────────────────────────────────────────────────────

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Train GNN world model offline")
    parser.add_argument("--config", type=str, default="configs/real.yaml")
    parser.add_argument("--use_gnn_world_model", type=str, default="true")
    parser.add_argument("--gnn_train", type=str, default="true")
    parser.add_argument("--gnn_data_dir", type=str, default=None)
    parser.add_argument("--gnn_checkpoint_dir", type=str, default=None)
    parser.add_argument("--gnn_epochs", type=int, default=None)
    parser.add_argument("--gnn_lr", type=float, default=None)
    parser.add_argument("--gnn_hidden_dim", type=int, default=None)
    parser.add_argument("--gnn_message_passing_steps", type=int, default=None)
    parser.add_argument("--enable_breakage", action="store_true")
    parser.add_argument("--enable_plasticity", action="store_true")
    args = parser.parse_args()

    cfg.load_from_yaml(args.config)

    # Override from CLI
    for attr in [
        "gnn_data_dir", "gnn_checkpoint_dir", "gnn_epochs",
        "gnn_lr", "gnn_hidden_dim", "gnn_message_passing_steps",
    ]:
        val = getattr(args, attr, None)
        if val is not None:
            setattr(cfg, attr, val)
    if args.enable_breakage:
        cfg.enable_breakage = True
    if args.enable_plasticity:
        cfg.enable_plasticity = True

    cfg.device = "cuda:0"
    run_gnn_training(args)
